In [22]:
import pandas as pd
df_1=pd.read_csv("title.basics.tsv", sep="\t")
df_1.shape

df_1.head(10)

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
0,tt0000001,short,Carmencita,Carmencita,0,1894,\N,1,"Documentary,Short"
1,tt0000002,short,Le clown et ses chiens,Le clown et ses chiens,0,1892,\N,5,"Animation,Short"
2,tt0000003,short,Poor Pierrot,Pauvre Pierrot,0,1892,\N,5,"Animation,Comedy,Romance"
3,tt0000004,short,Un bon bock,Un bon bock,0,1892,\N,12,"Animation,Short"
4,tt0000005,short,Blacksmith Scene,Blacksmith Scene,0,1893,\N,1,Short
5,tt0000006,short,Chinese Opium Den,Chinese Opium Den,0,1894,\N,1,Short
6,tt0000007,short,Corbett and Courtney Before the Kinetograph,Corbett and Courtney Before the Kinetograph,0,1894,\N,1,"Short,Sport"
7,tt0000008,short,Edison Kinetoscopic Record of a Sneeze,Edison Kinetoscopic Record of a Sneeze,0,1894,\N,1,"Documentary,Short"
8,tt0000009,movie,Miss Jerry,Miss Jerry,0,1894,\N,45,Romance
9,tt0000010,short,Leaving the Factory,La sortie de l'usine Lumière à Lyon,0,1895,\N,1,"Documentary,Short"

In [ ]:
df_1["runtimeMinutes"].dtype

df_1["runtimeMinutes"]= pd.to_numeric(df_1["runtimeMinutes"], errors="coerce")

df_1["runtimeMinutes"].isna()

df_1["runtimeMinutes"].isna().sum()

NanPercent=df_1["runtimeMinutes"].isna().sum()/len(df_1)*100
print(NanPercent)

64.22825720272269

      tconst  averageRating  numVotes
0  tt0000001            5.7      2188
1  tt0000002            5.5       308
2  tt0000003            6.5      2289
3  tt0000004            5.1       196
4  tt0000005            6.2      3019
5  tt0000006            5.1       221
6  tt0000007            5.3       933
7  tt0000008            5.4      2363
8  tt0000009            5.2       232
9  tt0000010            6.8      8209

In [ ]:


df_2= pd.read_csv("title.ratings.tsv", sep="\t" )
df_2.head(10)

df_2.isna().sum()

tconst           0
averageRating    0
numVotes         0
dtype: int64