Nettoyage de la base TMDB full (très sale), seule base permettant d'obtenir budget et nationalité.

Calcul des films par catégorie de budget et de nationalité

In [1]:
import os
print("Python WD =", os.getcwd())
print(os.listdir("."))

import pandas as pd
df_1=pd.read_csv("BDD/title.basics.tsv", sep="\t")
df_1.shape

df_1.head(30)

#df_1["genres"].value_counts()
#df_1["genres"].unique

Python WD = c:\Users\a-ray\Desktop\WCS\Projet_2
['BDD', 'df_final.csv', 'df_genres_5.csv', 'Exploration_genres_sans_court_métrage.ipynb', 'Fichier_trie.csv', 'mon_env_projet_2', 'projet_2.ipynb', 'projet_2_filter_complete.ipynb']

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
0,tt0000001,short,Carmencita,Carmencita,0,1894,\N,1,"Documentary,Short"
1,tt0000002,short,Le clown et ses chiens,Le clown et ses chiens,0,1892,\N,5,"Animation,Short"
2,tt0000003,short,Poor Pierrot,Pauvre Pierrot,0,1892,\N,5,"Animation,Comedy,Romance"
3,tt0000004,short,Un bon bock,Un bon bock,0,1892,\N,12,"Animation,Short"
4,tt0000005,short,Blacksmith Scene,Blacksmith Scene,0,1893,\N,1,Short
5,tt0000006,short,Chinese Opium Den,Chinese Opium Den,0,1894,\N,1,Short
6,tt0000007,short,Corbett and Courtney Before the Kinetograph,Corbett and Courtney Before the Kinetograph,0,1894,\N,1,"Short,Sport"
7,tt0000008,short,Edison Kinetoscopic Record of a Sneeze,Edison Kinetoscopic Record of a Sneeze,0,1894,\N,1,"Documentary,Short"
8,tt0000009,movie,Miss Jerry,Miss Jerry,0,1894,\N,45,Romance
9,tt0000010,short,Leaving the Factory,La sortie de l'usine Lumière à Lyon,0,1895,\N,1,"Documentary,Short"
10,tt0000011,short,Akrobatisches Potpourri,Akrobatisches Potpourri,0,1895,\N,1,"Documentary,Short"
11,tt0000012,short,The Arrival of a Train,L'arrivée d'un train à La Ciotat,0,1896,\N,1,"Documentary,Short"
12,tt0000013,short,The Photographical Congress Arrives in Lyon,Le débarquement du congrès de photographie à Lyon,0,1895,\N,1,"Documentary,Short"
13,tt0000014,short,The Waterer Watered,L'arroseur arrosé,0,1895,\N,1,"Comedy,Short"
14,tt0000015,short,Around a Cabin,Autour d'une cabine,0,1894,\N,2,"Animation,Comedy,Short"
15,tt0000016,short,Boat Leaving the Port,Barque sortant du port,0,1895,\N,1,"Documentary,Short"
16,tt0000017,short,Italienischer Bauerntanz,Italienischer Bauerntanz,0,1895,\N,1,"Documentary,Short"
17,tt0000018,short,Das boxende Känguruh,Das boxende Känguruh,0,1895,\N,1,"Short,Sport"
18,tt0000019,short,The Clown Barber,The Clown Barber,0,1898,\N,\N,"Comedy,Short"
19,tt0000020,short,The Derby 1895,The Derby 1895,0,1895,\N,1,"Documentary,Short,Sport"
20,tt0000022,short,Blacksmith Scene,Les forgerons,0,1895,\N,1,"Documentary,Short"
21,tt0000023,short,The Sea,Baignade en mer,0,1895,\N,1,"Documentary,Short"
22,tt0000024,short,Opening of the Kiel Canal,Opening of the Kiel Canal,0,1895,\N,1,"News,Short"
23,tt0000025,short,The Oxford and Cambridge University Boat Race,The Oxford and Cambridge University Boat Race,0,1896,\N,\N,"News,Short,Sport"
24,tt0000026,short,The Messers. Lumière at Cards,Partie d'écarté,0,1896,\N,1,"Documentary,Short"
25,tt0000027,short,Cordeliers' Square in Lyon,Place des Cordeliers à Lyon,0,1895,\N,1,"Documentary,Short"
26,tt0000028,short,Fishing for Goldfish,La pêche aux poissons rouges,0,1895,\N,1,"Documentary,Short"
27,tt0000029,short,Baby's Meal,Repas de bébé,0,1895,\N,1,"Documentary,Short"
28,tt0000030,short,Rough Sea at Dover,Rough Sea at Dover,0,1895,\N,1,"Documentary,Short"
29,tt0000031,short,Jumping the Blanket,Le saut à la couverture,0,1895,\N,1,"Documentary,Short"

In [2]:
df_1["runtimeMinutes"].dtype

df_1["runtimeMinutes"]= pd.to_numeric(df_1["runtimeMinutes"], errors="coerce")

df_1["runtimeMinutes"].isna()

df_1["runtimeMinutes"].isna().sum()

NanPercent=df_1["runtimeMinutes"].isna().sum()/len(df_1)*100

In [8]:


df_2= pd.read_csv("BDD/title.ratings.tsv", sep="\t" )
df_2.head(10)

df_2.isna().sum()

tconst           0
averageRating    0
numVotes         0
dtype: int64

In [ ]:
df_3.head(10)

film_fr = df_3[
    #(df_3["region"] == "FR") &
    #(df_3["isOriginalTitle"] == 1)]

film_fr.head(10)

df_3['region'].value_counts()

#df_3["isOriginalTitle"].value_counts()

df_3[df_3["isOriginalTitle"] == 1]["region"].value_counts(dropna=False).head()

NameError: name 'df_3' is not defined

In [9]:
df_5 = pd.read_csv(
    "BDD/tmdb_full.csv",
    engine="python",
    dtype=str,
    on_bad_lines="skip"
)

df_5.head(10)

df_5.shape

expected=311137
actual= df_5.shape[0]

loss_rate= 1- actual/expected

print(loss_rate)

0.8525504841918512

In [10]:
df_5.head(10)

,adult,backdrop_path,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count,production_companies_name,production_companies_country;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
0,False,/dvQj1GBZAZirz1skEEZyWH2ZqQP.jpg,0,['Comedy'],NaN,3924,tt0029927,en,Blondie,Blondie and Dagwood are about to celebrate the...,...,70,['en'],Released,The favorite comic strip of millions at last o...,Blondie,False,7.214,7,['Columbia Pictures'],['US'];;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
1,False,NaN,0,['Drama'],NaN,9,tt0425473,de,Sonntag im August,NaN,...,15,['de'],Released,NaN,Sunday in August,False,7.738,21,[],[];;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
2,False,NaN,0,['Comedy'],NaN,94,tt0436488,de,Kunstgriff,Kunstgriff is a brilliantly filmed black and w...,...,6,['xx'],Released,NaN,Kunstgriff,False,8.5,2,['Hamburger Filmschule'],['DE'];;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
3,False,/eTSRN1Bwce60rpAORwkKbPRDT6V.jpg,0,['Drama'],NaN,127,tt0084549,pl,Przypadek,Witek runs after a train. Three variations fol...,...,123,['pl'],Released,NaN,Blind Chance,False,7.538,158,['Film Polski'],['PL'];;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
4,False,/e6IPjjDzZDkgdkvxQtCjaVCMYJF.jpg,0,['Documentary'],NaN,133,tt0054205,en,Primary,Primary is a documentary film about the primar...,...,60,['en'],Released,NaN,Primary,False,6.462,26,['Drew Associates'],['US'];;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
5,False,/1K9YJzQ6r5nCrOVrjSnAmji8zLc.jpg,0,['Drama'],http://lantern-media.com/BronxGangs-Wanderers.htm,233,tt0080117,en,The Wanderers,The streets of the Bronx are owned by '60s you...,...,117,['en'],Released,It was The Wanderers against the world ... and...,The Wanderers,False,6.985,162,['Orion Pictures'],['US'];;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
6,False,/qJyv8aRRwPhI5jX98XMmluWEdDq.jpg,0,['Comedy'],http://www.crustaces-lefilm.com/,349,tt0428430,fr,Crustacés et coquillages,Crustacés et coquillages is a fresh French com...,...,93,['fr'],Released,NaN,Cockles and Muscles,False,6.1,28,['Bac Films'],['FR'];;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
7,False,NaN,10000,[],NaN,538,tt0485662,en,Janine F.,The humorous portrait of a female artist. The ...,...,52,['de'],Released,NaN,Janine F.,False,5.0,1,[],[];;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
8,False,/qmeFQVVx7qBBW8NE1ZNVh5PSwLS.jpg,0,['Thriller'],https://paradigmafilms.ch/en/absolut-3/,555,tt0442896,en,Absolut,Two guys against globalization want to plant a...,...,94,['fr'],Released,NaN,Absolut,False,7.8,23,['Paradigma Films'],['CH'];;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
9,False,/p47ihFj4A7EpBjmPHdTj4ipyq1S.jpg,1752000,['Drama'],NaN,599,tt0043014,en,Sunset Boulevard,A hack screenwriter writes a screenplay for a ...,...,110,['en'],Released,A Hollywood Story.,Sunset Boulevard,False,8.359,2208,['Paramount'],['US'];;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

In [11]:
df_6 = pd.read_csv(
    "BDD/tmdb_full.csv",
    engine="python",   
    dtype=str,         
    on_bad_lines="skip"
)

df_6.columns


df_6.iloc[:, -1] = df_6.iloc[:, -1].str.replace(";", "", regex=False)

df_6.head(10)


df_6["production_companies_country"] = df_6["production_companies_country;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;"].str.replace(";", "", regex=False)

df_6.head(10)

df_7=df_6.drop(columns=["production_companies_country;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;"])

df_7.head(10)


df_7[(df_7["original_language"]=="fr")]

,adult,backdrop_path,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count,production_companies_name,production_companies_country
6,False,/qJyv8aRRwPhI5jX98XMmluWEdDq.jpg,0,['Comedy'],http://www.crustaces-lefilm.com/,349,tt0428430,fr,Crustacés et coquillages,Crustacés et coquillages is a fresh French com...,...,93,['fr'],Released,NaN,Cockles and Muscles,False,6.1,28,['Bac Films'],['FR']
28,False,NaN,0,['Drama'],NaN,2388,tt0367266,fr,À San Remo,NaN,...,22,['fr'],Released,NaN,À San Remo,False,0.0,0,['Local Films'],['FR']
31,False,/rD43ymqeS6CtB20t1nx7jXj5RE2.jpg,0,['Drama'],NaN,2429,tt0072323,fr,Trop c'est trop,NaN,...,90,['fr'],Released,NaN,Trop c'est trop,False,5.7,3,['Félix Films'],['']
32,False,/4dN562ZiNzMSNo2S86VyQsvPcJU.jpg,0,['Comedy'],NaN,2437,tt0155522,fr,Le bahut va craquer,NaN,...,90,['fr'],Released,NaN,Le bahut va craquer,False,4.0,2,['Paris Prociné'],['']
35,False,NaN,0,['Crime'],NaN,2735,tt0174934,fr,Monsieur seul,No overview found.,...,240,['fr'],Released,NaN,Monsieur seul,False,0.0,0,[],[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45785,False,NaN,0,['Fantasy'],NaN,232713,tt0249435,fr,Le charmeur,A magician charms a caterpillar and turns it i...,...,4,['xx'],Released,NaN,The Charmer,False,5.5,4,['Pathé Frères'],
45803,False,NaN,0,['Documentary'],NaN,232932,tt1442625,fr,Le chemin noir,NaN,...,0,['fr'],Released,NaN,Le chemin noir,False,0.0,0,['La Vie Est Belle Films Associés'],
45805,False,NaN,0,[],NaN,232948,tt1804503,fr,Conscience de magistrat,The Magistrate's Conscience - A drama from Pat...,...,8,[],Released,NaN,Conscience de magistrat,False,5.0,1,[],
45806,False,NaN,0,['Animation'],NaN,232952,tt1003393,fr,Affaires de cœur,A near-abstract animation telling a simple rom...,...,4,['xx'],Released,NaN,Affairs of the Heart,False,5.5,8,['Gaumont'],
45807,False,NaN,0,['Comedy'],NaN,232957,tt0277596,fr,Le baromètre de la fidélité,This Max Linder short opens with him and his g...,...,15,['xx'],Released,NaN,The Barometer of Fidelity,False,5.0,4,['Pathé Frères'],

In [12]:
import numpy as np
import pandas as pd

df_7["budget"] = pd.to_numeric(df_7["budget"], errors="coerce")


conditions = [
    df_7["budget"].isna(),
    df_7["budget"]==0,                  
    (df_7["budget"] < 500_000) & (df_7["budget"]>1),             
    (df_7["budget"] >= 500_000) & (df_7["budget"] < 3_000_000),  
    df_7["budget"] >= 3_000_000             
]


choices = ["unknown", "0", "indé pur", "cinéma indépendant", "blockbuster"]


df_7["budget_category"] = np.select(conditions, choices, default="unknown")

vc_budget=df_7["budget_category"].value_counts()

In [13]:


df_7["original_language"].value_counts().head(45).to_frame()

                   count
original_language
en                 19565
de                  4950
es                  3412
fr                  2551
ja                  2141
it                  1763
pt                  1067
tr                   867
ru                   853
zh                   723
cs                   695
nl                   517
sv                   446
da                   419
hi                   396
el                   347
pl                   337
ml                   327
tl                   324
ta                   265
hu                   258
fi                   252
cn                   225
bn                   190
fa                   176
xx                   166
te                   164
ko                   160
ar                   130
sk                    95
no                    93
ro                    87
he                    82
sh                    79
mr                    74
kn                    70
id                    69
or                    53
uk                    48
pa                    44
mk                    44
hr                    44
th                    43
bg                    39
ca                    38

In [15]:
vc=df_7["original_language"].value_counts()

In [16]:
import plotly.express as px

px.pie(names=vc.head(5).index, values=vc.head(5).values)

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'domain': {'x': [0.0, 1.0], 'y': [0.0, 1.0]},
              'hovertemplate': 'label=%{label}<br>value=%{value}<extra></extra>',
              'labels': array(['en', 'de', 'es', 'fr', 'ja'], dtype=object),
              'legendgroup': '',
              'name': '',
              'showlegend': True,
              'type': 'pie',
              'values': {'bdata': 'bUxWE1QN9wldCA==', 'dtype': 'i2'}}],
    'layout': {'legend': {'tracegroupgap': 0}, 'margin': {'t': 60}, 'template': '...'}
})

In [17]:
px.bar(vc.head(15), x=vc.head(15).index, y="count")

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'hovertemplate': 'x=%{x}<br>count=%{y}<extra></extra>',
              'legendgroup': '',
              'marker': {'color': '#636efa', 'pattern': {'shape': ''}},
              'name': '',
              'orientation': 'v',
              'showlegend': False,
              'textposition': 'auto',
              'type': 'bar',
              'x': array(['en', 'de', 'es', 'fr', 'ja', 'it', 'pt', 'tr', 'ru', 'zh', 'cs', 'nl',
                          'sv', 'da', 'hi'], dtype=object),
              'xaxis': 'x',
              'y': {'bdata': 'bUxWE1QN9wldCOMGKwRjA1UD0wK3AgUCvgGjAYwB', 'dtype': 'i2'},
              'yaxis': 'y'}],
    'layout': {'barmode': 'relative',
               'legend': {'tracegroupgap': 0},
               'margin': {'t': 60},
               'template': '...',
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': 'x'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'count'}}}
})

In [18]:
px.pie(names=vc_budget.tail(4).index, values=vc_budget.tail(4).values)

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'domain': {'x': [0.0, 1.0], 'y': [0.0, 1.0]},
              'hovertemplate': 'label=%{label}<br>value=%{value}<extra></extra>',
              'labels': array(['indé pur', 'unknown', 'cinéma indépendant', 'blockbuster'],
                              dtype=object),
              'legendgroup': '',
              'name': '',
              'showlegend': True,
              'type': 'pie',
              'values': {'bdata': 'mATxAqsAUQA=', 'dtype': 'i2'}}],
    'layout': {'legend': {'tracegroupgap': 0}, 'margin': {'t': 60}, 'template': '...'}
})

In [19]:
df_7["original_language"].apply(type).head(10)

0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: original_language, dtype: object

In [20]:
lang_europe = {
    "de","es","pt","pl","sv","sk","it","ro","nl","da","no","is",
    "ru","cs","sl","hr","sr","be","uk","mk","bs","el","hy","sq", "et", "ca", "fi", "hu", "lv", "lt", "bg"
}

def classify(lang):
    if pd.isna(lang):
        return "unknown"
    if lang == "fr":
        return "français"
    if lang == "en":
        return "langue anglaise"
    if lang in lang_europe:
        return "européen"
    return "unknown"

df_7["origine"] = df_7["original_language"].apply(classify)

df_7["origine"].value_counts()

df_7["runtime"]

0         70
1         15
2          6
3        123
4         60
        ...
45872     70
45873      0
45874     76
45875      0
45876     64
Name: runtime, Length: 45877, dtype: object

In [22]:
df_7["startYear"].astype(int)

bins = [0, 1980, 2000, 2015, 2100]
period_labels = ['Classiques', 'Modernes', 'Récents', 'Très récents']

df_7['period'] = pd.cut(
    df_7['startYear'],
    bins=bins,
    labels=period_labels)

df_7["budget_category"].value_counts()

KeyError: 'startYear'

In [23]:
df_7["budget_category"].value_counts()

budget_category
0                     43696
indé pur               1176
unknown                 753
cinéma indépendant      171
blockbuster              81
Name: count, dtype: int64

In [24]:
df_8=pd.read_csv("df_genres_5.csv", sep=",")

df_8

,tconst,originalTitle,startYear,genres
0,tt0015724,Dama de noche,1993.0,Drama
1,tt0015724,Dama de noche,1993.0,Romance
2,tt0022064,Lebbra bianca,1951.0,Drama
3,tt0024121,Houkutuslintu,1946.0,Drama
4,tt0025557,El negro que tenía el alma blanca,1951.0,Drama
...,...,...,...,...
387031,tt9916190,Safeguard,2020.0,Action
387032,tt9916362,Akelarre,2020.0,Drama
387033,tt9916538,Kuambil Lagi Hatiku,2019.0,Drama
387034,tt9916680,De la ilusión al desconcierto: cine colombiano...,2007.0,Documentary
387035,tt9916730,6 Gunn,2017.0,Drama

In [38]:
df_9=pd.merge(df_8, df_7, how="left", left_on="tconst", right_on="imdb_id")

df_9.drop(columns=["adult", "genres_y", "id", "imdb_id", "status", "tagline", "title", "vote_average", "vote_count"])

df_9.shape


df_9.head(10)

df_9["startYear"].astype(int)

bins = [0, 1980, 2000, 2015, 2100]
period_labels = ['Classiques', 'Modernes', 'Récents', 'Très récents']

df_9['period'] = pd.cut(
    df_9['startYear'],
    bins=bins,
    labels=period_labels)

df_9["period"].value_counts()

period
Très récents    125630
Récents         124512
Classiques       76498
Modernes         60396
Name: count, dtype: int64

In [36]:
df_10 = df_9.dropna(subset=["origine"])

df_10.shape

df_10["origine"].value_counts()

origine
européen           6950
langue anglaise    5498
unknown            4232
français            728
Name: count, dtype: int64

In [35]:
df_10 = df_9.dropna(subset=["origine"])

df_10.shape

df_10["origine"].value_counts()

df_11 = df_10[~df_10["origine"].isin(["langue anglaise", "unknown"])]

df_11

df_11["budget_category"].value_counts()

budget_category
0                     7536
indé pur                71
cinéma indépendant      47
blockbuster             24
Name: count, dtype: int64

In [28]:
df_11.to_csv("Fichier_trie.csv")

In [34]:
df_7["origine"].value_counts()

df_10["startYear"]=df_10["startYear"].astype(int)
df_10[df_10["origine"]=="français"]

C:\Users\a-ray\AppData\Local\Temp\ipykernel_8760\2016319509.py:3: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,tconst,originalTitle,startYear,genres_x,adult,backdrop_path,budget,genres_y,homepage,id,...,tagline,title,video,vote_average,vote_count,production_companies_name,production_companies_country,budget_category,origine,period
21,tt0031084,Battement de coeur,1940,Comedy,False,/yMXeoilZAncXAQdTK5jt2U4zebx.jpg,0.0,['Drama'],NaN,257050,...,NaN,Beating Heart,False,6.3,15,['Ciné-Alliance'],,0,français,Classiques
22,tt0031084,Battement de coeur,1940,Drama,False,/yMXeoilZAncXAQdTK5jt2U4zebx.jpg,0.0,['Drama'],NaN,257050,...,NaN,Beating Heart,False,6.3,15,['Ciné-Alliance'],,0,français,Classiques
221,tt0032350,La comédie du bonheur,1940,Comedy,False,NaN,0.0,[],NaN,132273,...,NaN,Comedy of Happiness,False,5.7,3,[],,0,français,Classiques
2018,tt0034660,Don Cesare di Bazan,1942,Comedy,False,NaN,0.0,['Comedy'],NaN,131749,...,NaN,Don Cesare di Bazan,False,0.0,0,[],,0,français,Classiques
2567,tt0035336,Simplet,1942,Comedy,False,/nRFG9WLV21vgLFAacNs1WLgBj4K.jpg,0.0,['Comedy'],NaN,85730,...,NaN,Simple-Minded,False,6.0,4,['Continental Films'],,0,français,Classiques
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
382392,tt9238380,Internet Etc.,2018,Documentary,False,/w2mQJ19PZlHwbylVvvzh1Jkzw9s.jpg,0.0,['Comedy'],NaN,537060,...,NaN,Haroun - Internet Etc.,False,7.9,7,[],[],0,français,Très récents
382691,tt9279848,Chasseurs de phoques,2018,Documentary,False,/kM6SDbxSZr56LhdpITZ7vWpf3xH.jpg,0.0,['Documentary'],NaN,566939,...,NaN,Chasseurs de phoques,False,0.0,0,['MC2 Productions'],['CA'],0,français,Très récents
383009,tt9330648,Tu te souviendras de moi,2020,Drama,False,/chBIXItaUtfAzsIjOhqndGvDpSE.jpg,0.0,['Drama'],http://corinthfilms.com/films/you-will-remembe...,633929,...,A story told. A life relived.,You Will Remember Me,False,5.0,2,['Christal Films'],['CA'],0,français,Très récents
384366,tt9562296,Asking for It,2020,Comedy,False,/ngXWSkI8i46hirjTMBV01uXONPn.jpg,0.0,['Crime'],NaN,705134,...,NaN,Asking For It,False,7.5,2,[],[],0,français,Très récents
386838,tt9890024,Ensemble,2018,Documentary,False,/fZEIUrVOXz3qp2YPcLS8UfW1254.jpg,0.0,['Documentary'],NaN,560134,...,NaN,Ensemble,False,0.0,0,['Films JAD'],['CA'],0,français,Très récents

In [30]:
df_12= pd.read_csv("BDD/title.basics.tsv", sep="\t")

In [95]:
#df_12=df_12.drop(columns=["titleType", "primaryTitle", "originalTitle", "isAdult", "endYear", "genres"])

df_final= pd.merge(df_11, df_12, how="left", left_on="tconst", right_on="tconst")

df_final["budget_category"].value_counts()

df_final.to_csv("df_final.csv")

df_final

df_final.isna().sum()

tconst                             0
originalTitle                      0
startYear_x                        0
genres_x                           0
adult                              0
backdrop_path                   5348
budget                             0
genres_y                           0
homepage                        7525
id                                 0
imdb_id                            0
original_language                  0
original_title                     0
overview                        4807
popularity                         0
poster_path                     1454
production_countries               0
release_date                     237
revenue                            0
runtime                            0
spoken_languages                   0
status                             0
tagline                         7541
title                              0
video                              0
vote_average                       0
vote_count                         0
production_companies_name          0
production_companies_country       0
budget_category                    0
origine                            0
period                             0
startYear_y                        0
runtimeMinutes                     0
dtype: int64

In [94]:
df_final=df_final.drop(columns=["genres_y", "video"])

df_final=df_final.drop(columns=["startYear_x"])

In [99]:
df_nom= pd.read_csv("BDD/fichier_nom.csv", sep=",")

df_nom = df_nom.drop_duplicates(subset=['tconst'])

print(df_nom.columns)
print(df_final.columns)

df_final2=pd.merge(df_final, df_nom, how="left", left_on=["tconst"], right_on=["tconst"])

df_final2=df_final2.drop(columns=['overview', 'popularity','original_title','production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', ])

df_final2


df_final_2.to_csv("df_final_2.csv")

Index(['tconst', 'directors', 'actors'], dtype='object')
Index(['tconst', 'originalTitle', 'startYear_x', 'genres_x', 'adult',
       'backdrop_path', 'budget', 'genres_y', 'homepage', 'id', 'imdb_id',
       'original_language', 'original_title', 'overview', 'popularity',
       'poster_path', 'production_countries', 'release_date', 'revenue',
       'runtime', 'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count', 'production_companies_name',
       'production_companies_country', 'budget_category', 'origine', 'period',
       'startYear_y', 'runtimeMinutes'],
      dtype='object')